Move the 'delete list' option to the Activity
So, calling PocketContentProvider.delete(uri,null,null) works fine with
a ListView, but (starting with commit 68751a4500b55ac5306cc55ccb2081682d3d169a)
I moved to using a ViewFlipper to give me the left/right swiping ability.

This caused a crash whenever I tried deleting the whole DB (See the
end of this commit for the stacktrace). I could not figure out what
exactly was happening. I even destroyed the fragments loader before
doing the delete, but it still tried updating. ListView didn't have
this problem, so I think I am just trying to use ViewFlipper for something
it isn't really meant for.

Just removing the whole fragment from the Activity level before doing the
delete fixed the crash. This should be fine for now as 'delete list' is
mostly for development and likely won't be in the final app.

CRASH LOG START
=======================
09-13 17:51:45.149    8488-8488/com.astronaut_wannabe.pocketutil E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.astronaut_wannabe.pocketutil, PID: 8488
    java.lang.IllegalStateException: couldn't move cursor to position 0
            at android.widget.CursorAdapter.getView(CursorAdapter.java:246)
            at android.widget.AdapterViewAnimator.refreshChildren(AdapterViewAnimator.java:416)
            at android.widget.AdapterViewAnimator$2.run(AdapterViewAnimator.java:749)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5059)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)